# Generated by Django 3.2.16 on 2025-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subsription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsription',
            name='comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
